City.create([{name: 'Bogotá'},
	{name: 'Cali'},
	{name: 'Medellín'},
	{name: 'Cartagena'},
	{name: 'Barranquilla'},
	{name: 'Bucaramanga'},
	{name: 'Santa Marta'},
	{name: 'Cúcuta'},
	{name: 'Manizales'},
	{name: 'Ibagué'},
	{name: 'Pereira'},
	{name: 'Villavicencio'},
	{name: 'Pasto'},
	{name: 'Montería'},
	{name: 'Valledupar'},
	{name: 'Neiva'},
	{name: 'Armenia'},
	{name: 'Tunja'},
	{name: 'Popayán'},
	{name: 'Sincelejo'},
	{name: 'Buenaventura'},
	{name: 'Soacha'},
	{name: 'Riohacha'},
	{name: 'Soledad'},
	{name: 'Yopal'},
	{name: 'Florencia'},
	{name: 'Quibdó'},
	{name: 'Palmira'},
	{name: 'Bello'},
	{name: 'Leticia'},
	{name: 'Barrancabermeja'},
	{name: 'Ipiales'},
	{name: 'Tuluá'},
	{name: 'Sogamoso'},
	{name: 'Jamundí'},
	{name: 'Facatativá'},
	{name: 'Zipaquirá'},
	{name: 'Girardot'},
	{name: 'Itaguí'},
	{name: 'Floridablanca'},
	{name: 'Mocoa'},
	{name: 'Puerto Carreño'},
	{name: 'Buga'},
	{name: 'Tumaco'},
	{name: 'Duitama'},
	{name: 'Mitú'},
	{name: 'Apartadó'},
	{name: 'Ocaña'},
	{name: 'San Jose del Guaviare'},
	{name: 'San Juan del Girón'},
	{name: 'Ciénaga'}])


Department.create([{name: 'Amazonas'},
	{name: 'Antioquia'},
	{name: 'Arauca'},
	{name: 'Archipiélago de San Andrés'},
	{name: 'Atlántico'},
	{name: 'Bogotá D.C.'},
	{name: 'Bolívar'},
	{name: 'Boyacá'},
	{name: 'Caldas'},
	{name: 'Caquetá'},
	{name: 'Casanare'},
	{name: 'Cauca'},
	{name: 'Cesar'},
	{name: 'Chocó'},
	{name: 'Córdoba'},
	{name: 'Cundinamarca'},
	{name: 'Guainía'},
	{name: 'Guaviare'},
	{name: 'Huila'},
	{name: 'La Guajira'},
	{name: 'Magdalena'},
	{name: 'Meta'},
	{name: 'Nariño'},
	{name: 'Norte de Santander'},
	{name: 'Putumayo'},
	{name: 'Quindío'},
	{name: 'Risaralda'},
	{name: 'Santander'},
	{name: 'Sucre'},
	{name: 'Tolima'},
	{name: 'Valle del Cauca'},
	{name: 'Vaupés'},
	{name: 'Vichada'}])

